# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1109, 787)
        self.textEdit_Secuencia1 = QtWidgets.QTextEdit(Form)
        self.textEdit_Secuencia1.setGeometry(QtCore.QRect(50, 110, 421, 81))
        self.textEdit_Secuencia1.setObjectName("textEdit_Secuencia1")
        self.textEdit_Secuencia2 = QtWidgets.QTextEdit(Form)
        self.textEdit_Secuencia2.setGeometry(QtCore.QRect(50, 240, 421, 81))
        self.textEdit_Secuencia2.setObjectName("textEdit_Secuencia2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 80, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 210, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(300, 70, 341, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 30, 791, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_Audio1 = QtWidgets.QPushButton(Form)
        self.pushButton_Audio1.setGeometry(QtCore.QRect(580, 150, 141, 41))
        self.pushButton_Audio1.setObjectName("pushButton_Audio1")
        self.pushButton_Audio2 = QtWidgets.QPushButton(Form)
        self.pushButton_Audio2.setGeometry(QtCore.QRect(580, 280, 141, 41))
        self.pushButton_Audio2.setObjectName("pushButton_Audio2")
        self.label_RutaAudio1 = QtWidgets.QLabel(Form)
        self.label_RutaAudio1.setGeometry(QtCore.QRect(530, 110, 291, 16))
        self.label_RutaAudio1.setObjectName("label_RutaAudio1")
        self.label_RutaAudio2 = QtWidgets.QLabel(Form)
        self.label_RutaAudio2.setGeometry(QtCore.QRect(530, 240, 291, 16))
        self.label_RutaAudio2.setObjectName("label_RutaAudio2")
        self.pushButton_Calcular = QtWidgets.QPushButton(Form)
        self.pushButton_Calcular.setGeometry(QtCore.QRect(50, 340, 191, 51))
        self.pushButton_Calcular.setObjectName("pushButton_Calcular")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(800, 50, 281, 381))
        self.groupBox.setObjectName("groupBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(60, 290, 21, 21))
        self.label_7.setObjectName("label_7")
        self.spinBox_n0 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_n0.setGeometry(QtCore.QRect(90, 190, 42, 22))
        self.spinBox_n0.setMinimum(-10000)
        self.spinBox_n0.setMaximum(10000)
        self.spinBox_n0.setObjectName("spinBox_n0")
        self.spinBox_KDiezm = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_KDiezm.setGeometry(QtCore.QRect(90, 240, 42, 22))
        self.spinBox_KDiezm.setMinimum(-10000)
        self.spinBox_KDiezm.setMaximum(10000)
        self.spinBox_KDiezm.setObjectName("spinBox_KDiezm")
        self.radioButton_Diezmacion = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Diezmacion.setGeometry(QtCore.QRect(140, 240, 95, 20))
        self.radioButton_Diezmacion.setObjectName("radioButton_Diezmacion")
        self.radioButton_Convolucion = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Convolucion.setGeometry(QtCore.QRect(140, 330, 95, 20))
        self.radioButton_Convolucion.setObjectName("radioButton_Convolucion")
        self.spinBox_KInterp = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_KInterp.setGeometry(QtCore.QRect(90, 290, 42, 22))
        self.spinBox_KInterp.setMinimum(-10000)
        self.spinBox_KInterp.setMaximum(10000)
        self.spinBox_KInterp.setObjectName("spinBox_KInterp")
        self.radioButton_Interpolacion = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Interpolacion.setGeometry(QtCore.QRect(140, 290, 95, 20))
        self.radioButton_Interpolacion.setObjectName("radioButton_Interpolacion")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 190, 31, 21))
        self.label_5.setObjectName("label_5")
        self.radioButton_Multiplicacion = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Multiplicacion.setGeometry(QtCore.QRect(140, 110, 121, 20))
        self.radioButton_Multiplicacion.setObjectName("radioButton_Multiplicacion")
        self.radioButton_Suma = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Suma.setGeometry(QtCore.QRect(140, 30, 95, 20))
        self.radioButton_Suma.setObjectName("radioButton_Suma")
        self.radioButton_Reflexion = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Reflexion.setGeometry(QtCore.QRect(140, 150, 95, 20))
        self.radioButton_Reflexion.setObjectName("radioButton_Reflexion")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(60, 240, 21, 21))
        self.label_6.setObjectName("label_6")
        self.radioButton_Desplazamiento = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Desplazamiento.setGeometry(QtCore.QRect(140, 190, 121, 20))
        self.radioButton_Desplazamiento.setObjectName("radioButton_Desplazamiento")
        self.radioButton_Resta = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Resta.setGeometry(QtCore.QRect(140, 70, 95, 20))
        self.radioButton_Resta.setObjectName("radioButton_Resta")
        self.label_Status = QtWidgets.QLabel(Form)
        self.label_Status.setGeometry(QtCore.QRect(310, 350, 351, 16))
        self.label_Status.setObjectName("label_Status")

        self.retranslateUi(Form)
        self.radioButton_Reflexion.toggled['bool'].connect(self.textEdit_Secuencia2.setDisabled) # type: ignore
        self.radioButton_Desplazamiento.toggled['bool'].connect(self.textEdit_Secuencia2.setDisabled) # type: ignore
        self.radioButton_Diezmacion.toggled['bool'].connect(self.textEdit_Secuencia2.setDisabled) # type: ignore
        self.radioButton_Interpolacion.toggled['bool'].connect(self.textEdit_Secuencia2.setDisabled) # type: ignore
        self.radioButton_Reflexion.toggled['bool'].connect(self.pushButton_Audio2.setDisabled) # type: ignore
        self.radioButton_Desplazamiento.toggled['bool'].connect(self.pushButton_Audio2.setDisabled) # type: ignore
        self.radioButton_Diezmacion.toggled['bool'].connect(self.pushButton_Audio2.setDisabled) # type: ignore
        self.radioButton_Interpolacion.toggled['bool'].connect(self.pushButton_Audio2.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Secuencia 1"))
        self.label_2.setText(_translate("Form", "Secuencia 2"))
        self.label_3.setText(_translate("Form", "Ejemplo:{5,7,*9,3,4,6,1} o {6,8,1,2,4,8*,9,7}"))
        self.label_4.setText(_translate("Form", "Intrucciones: Ingresar la secuenciaen los cuadros de texto, tal y como lo indica el ejemplo, el origen lo puede indicar con un asterisco"))
        self.pushButton_Audio1.setText(_translate("Form", "Audio1"))
        self.pushButton_Audio2.setText(_translate("Form", "Audio2"))
        self.label_RutaAudio1.setText(_translate("Form", "TextLabel"))
        self.label_RutaAudio2.setText(_translate("Form", "TextLabel"))
        self.pushButton_Calcular.setText(_translate("Form", "Calcular"))
        self.groupBox.setTitle(_translate("Form", "Operaciones"))
        self.label_7.setText(_translate("Form", "k ="))
        self.radioButton_Diezmacion.setText(_translate("Form", "Diezmacion"))
        self.radioButton_Convolucion.setText(_translate("Form", "Convolucion"))
        self.radioButton_Interpolacion.setText(_translate("Form", "Interpolacion"))
        self.label_5.setText(_translate("Form", "n0 ="))
        self.radioButton_Multiplicacion.setText(_translate("Form", "Multiplicacion"))
        self.radioButton_Suma.setText(_translate("Form", "Suma"))
        self.radioButton_Reflexion.setText(_translate("Form", "Reflexion"))
        self.label_6.setText(_translate("Form", "k ="))
        self.radioButton_Desplazamiento.setText(_translate("Form", "Desplazamiento"))
        self.radioButton_Resta.setText(_translate("Form", "Resta"))
        self.label_Status.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
